
batch 0 of 13 done
batch 1 of 13 done
batch 2 of 13 done
batch 3 of 13 done
batch 4 of 13 done
batch 5 of 13 done
batch 6 of 13 done
batch 7 of 13 done
batch 8 of 13 done
batch 9 of 13 done
batch 10 of 13 done
batch 11 of 13 done
batch 12 of 13 done
Traceback (most recent call last):
  File "fine_tune.py", line 273, in <module>
    train_epoch_losses, val_epoch_losses = run(config, train_dataset, val_dataset)
  File "fine_tune.py", line 179, in run
    val_correlation = inference(model)
  File "fine_tune.py", line 131, in inference
    val_words = list(pd.read_csv('./val_words.txt', header=None, names=['words'])['words'])
  File "/home/hhansen/decon/decon_env/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/hhansen/decon/decon_env/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/hhansen/decon/decon_env/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/hhansen/decon/decon_env/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/hhansen/decon/decon_env/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File ./val_words.txt does not exist: './val_words.txt'